#pragma once

#include "value_if.h"

#define GET_ARG_1(X, ...) X
#define GET_ARG_2(X, ...) GET_ARG_1(__VA_ARGS__)
#define GET_ARG_3(X, ...) GET_ARG_2(__VA_ARGS__)
#define GET_ARG_4(X, ...) GET_ARG_3(__VA_ARGS__)
#define GET_ARG_5(X, ...) GET_ARG_4(__VA_ARGS__)
#define GET_ARG_6(X, ...) GET_ARG_5(__VA_ARGS__)
#define GET_ARG_7(X, ...) GET_ARG_6(__VA_ARGS__)
#define GET_ARG_8(X, ...) GET_ARG_7(__VA_ARGS__)
#define GET_ARG_9(X, ...) GET_ARG_8(__VA_ARGS__)

#define GET_ARG(i, ...) GET_ARG_##i(__VA_ARGS__)


#define GET_ARGS_FROM_1(X1, X2, X3, X4, X5, X6, X7, X8, X9) X1 PREFIX_COMMA(X2) PREFIX_COMMA(X3) PREFIX_COMMA(X4) PREFIX_COMMA(X5) PREFIX_COMMA(X6) PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_2(X1, X2, X3, X4, X5, X6, X7, X8, X9) X2 PREFIX_COMMA(X3) PREFIX_COMMA(X4) PREFIX_COMMA(X5) PREFIX_COMMA(X6) PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_3(X1, X2, X3, X4, X5, X6, X7, X8, X9) X3 PREFIX_COMMA(X4) PREFIX_COMMA(X5) PREFIX_COMMA(X6) PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_4(X1, X2, X3, X4, X5, X6, X7, X8, X9) X4 PREFIX_COMMA(X5) PREFIX_COMMA(X6) PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_5(X1, X2, X3, X4, X5, X6, X7, X8, X9) X5 PREFIX_COMMA(X6) PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_6(X1, X2, X3, X4, X5, X6, X7, X8, X9) X6 PREFIX_COMMA(X7) PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_7(X1, X2, X3, X4, X5, X6, X7, X8, X9) X7 PREFIX_COMMA(X8) PREFIX_COMMA(X9)
#define GET_ARGS_FROM_8(X1, X2, X3, X4, X5, X6, X7, X8, X9) X8 PREFIX_COMMA(X9)
#define GET_ARGS_FROM_9(X1, X2, X3, X4, X5, X6, X7, X8, X9) X9

#define GET_ARGS_FROM(i, ...) GET_ARGS_FROM_##i(__VA_ARGS__)